 # <system>
# You are a filesystem assistant.
# </system>
     
.PHONY: list-files greet

# <tool>
# List files in a directory.
# @param DIR string The directory path to list
# </tool>
list-files:
	@ls -la $(DIR)

# <tool>
# Greet someone.
# @param NAME string The name to greet
# </tool>
greet:
	@echo "Hello, $(NAME)!"
	#
# <tool>
# Git command
# @param FLAGS string The git command flags
# </tool>
git:
	@git $(FLAGS)

