"""Constants for the agent core module."""

DEFAULT_MAX_RETRIES = 5
DEFAULT_TOOL_TIMEOUT = 600  # seconds
DEFAULT_MAX_TOOL_OUTPUT = 32000  # characters; 0 = unlimited
DEFAULT_MAX_TOKENS = 4096
DEFAULT_REASONING_EFFORT = "medium"
DEFAULT_USE_PROMPT_CACHE = False
MAX_REPEATED_FAILURES = 8
MAX_MODEL_TURNS_PER_REQUEST = 64
MAX_TOOL_CALLS_PER_REQUEST = 256
MAX_RUN_SECONDS_PER_REQUEST = 900

DEFAULT_COMPACT_THRESHOLD_RATIO = 0.75
DEFAULT_COMPACT_MIN_THRESHOLD = 24_000
DEFAULT_COMPACT_MAX_THRESHOLD = 100_000
